on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'print floder befor contents'
        run: ls

      - uses: actions/checkout@v3

      - name: 'print floder after contents'
        run: ls

      
